// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: protobuf.proto

package razpravljalnica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MessageBoard_CreateUser_FullMethodName            = "/razpravljalnica.MessageBoard/CreateUser"
	MessageBoard_CreateTopic_FullMethodName           = "/razpravljalnica.MessageBoard/CreateTopic"
	MessageBoard_PostMessage_FullMethodName           = "/razpravljalnica.MessageBoard/PostMessage"
	MessageBoard_UpdateMessage_FullMethodName         = "/razpravljalnica.MessageBoard/UpdateMessage"
	MessageBoard_DeleteMessage_FullMethodName         = "/razpravljalnica.MessageBoard/DeleteMessage"
	MessageBoard_LikeMessage_FullMethodName           = "/razpravljalnica.MessageBoard/LikeMessage"
	MessageBoard_GetSubscriptionNode_FullMethodName   = "/razpravljalnica.MessageBoard/GetSubscriptionNode"
	MessageBoard_ListTopics_FullMethodName            = "/razpravljalnica.MessageBoard/ListTopics"
	MessageBoard_GetMessages_FullMethodName           = "/razpravljalnica.MessageBoard/GetMessages"
	MessageBoard_SubscribeTopic_FullMethodName        = "/razpravljalnica.MessageBoard/SubscribeTopic"
	MessageBoard_TransferData_FullMethodName          = "/razpravljalnica.MessageBoard/TransferData"
	MessageBoard_SignalNewTail_FullMethodName         = "/razpravljalnica.MessageBoard/SignalNewTail"
	MessageBoard_HeartBeat_FullMethodName             = "/razpravljalnica.MessageBoard/HeartBeat"
	MessageBoard_AssignChainNode_FullMethodName       = "/razpravljalnica.MessageBoard/AssignChainNode"
	MessageBoard_ForwardBatch_FullMethodName          = "/razpravljalnica.MessageBoard/ForwardBatch"
	MessageBoard_ReadLike_FullMethodName              = "/razpravljalnica.MessageBoard/ReadLike"
	MessageBoard_ReadUser_FullMethodName              = "/razpravljalnica.MessageBoard/ReadUser"
	MessageBoard_ReadTopic_FullMethodName             = "/razpravljalnica.MessageBoard/ReadTopic"
	MessageBoard_ReadMessage_FullMethodName           = "/razpravljalnica.MessageBoard/ReadMessage"
	MessageBoard_ListTopicsFromInner_FullMethodName   = "/razpravljalnica.MessageBoard/ListTopicsFromInner"
	MessageBoard_ListMessagesFromInner_FullMethodName = "/razpravljalnica.MessageBoard/ListMessagesFromInner"
)

// MessageBoardClient is the client API for MessageBoard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageBoardClient interface {
	// Creates a new user and assigns it an id
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Creates a new topic to which users can post messages
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Topic, error)
	// Post a message to a topic; Succed only if the User and the Topic exist in the data base.
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*Message, error)
	// Update an existing message. Allowed only for the user who posted the message.
	UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*Message, error)
	// Delete an existing message. Allowed only for the user who posted the message.
	DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Like an existing message. Return the message with the new number of likes.
	LikeMessage(ctx context.Context, in *LikeMessageRequest, opts ...grpc.CallOption) (*Message, error)
	// Request a node to which a subscription can be opened.
	GetSubscriptionNode(ctx context.Context, in *SubscriptionNodeRequest, opts ...grpc.CallOption) (*SubscriptionNodeResponse, error)
	// Returns all the topics
	ListTopics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	// Returns messages in a topic
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	// Subscribe to topics; goes to the node returned by head
	SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (MessageBoard_SubscribeTopicClient, error)
	// Sync the old tail and the new tail
	TransferData(ctx context.Context, opts ...grpc.CallOption) (MessageBoard_TransferDataClient, error)
	// Signal that a new tail has been added
	SignalNewTail(ctx context.Context, in *SyncTailsRequest, opts ...grpc.CallOption) (*SyncTailsACK, error)
	HeartBeat(ctx context.Context, in *HearthBeatRequest, opts ...grpc.CallOption) (*HearthBeatResponse, error)
	AssignChainNode(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*ACK, error)
	ForwardBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
	ReadLike(ctx context.Context, in *ReadLikeRequest, opts ...grpc.CallOption) (*Like, error)
	ReadUser(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*User, error)
	ReadTopic(ctx context.Context, in *ReadTopicRequest, opts ...grpc.CallOption) (*Topic, error)
	ReadMessage(ctx context.Context, in *ReadMessageRequest, opts ...grpc.CallOption) (*Message, error)
	ListTopicsFromInner(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error)
	ListMessagesFromInner(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMessagesResponse, error)
}

type messageBoardClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageBoardClient(cc grpc.ClientConnInterface) MessageBoardClient {
	return &messageBoardClient{cc}
}

func (c *messageBoardClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, MessageBoard_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*Topic, error) {
	out := new(Topic)
	err := c.cc.Invoke(ctx, MessageBoard_CreateTopic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoard_PostMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) UpdateMessage(ctx context.Context, in *UpdateMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoard_UpdateMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) DeleteMessage(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageBoard_DeleteMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) LikeMessage(ctx context.Context, in *LikeMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoard_LikeMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) GetSubscriptionNode(ctx context.Context, in *SubscriptionNodeRequest, opts ...grpc.CallOption) (*SubscriptionNodeResponse, error) {
	out := new(SubscriptionNodeResponse)
	err := c.cc.Invoke(ctx, MessageBoard_GetSubscriptionNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ListTopics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, MessageBoard_ListTopics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, MessageBoard_GetMessages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) SubscribeTopic(ctx context.Context, in *SubscribeTopicRequest, opts ...grpc.CallOption) (MessageBoard_SubscribeTopicClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageBoard_ServiceDesc.Streams[0], MessageBoard_SubscribeTopic_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &messageBoardSubscribeTopicClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageBoard_SubscribeTopicClient interface {
	Recv() (*MessageEvent, error)
	grpc.ClientStream
}

type messageBoardSubscribeTopicClient struct {
	grpc.ClientStream
}

func (x *messageBoardSubscribeTopicClient) Recv() (*MessageEvent, error) {
	m := new(MessageEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageBoardClient) TransferData(ctx context.Context, opts ...grpc.CallOption) (MessageBoard_TransferDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageBoard_ServiceDesc.Streams[1], MessageBoard_TransferData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &messageBoardTransferDataClient{stream}
	return x, nil
}

type MessageBoard_TransferDataClient interface {
	Send(*UploadData) error
	CloseAndRecv() (*UploadACK, error)
	grpc.ClientStream
}

type messageBoardTransferDataClient struct {
	grpc.ClientStream
}

func (x *messageBoardTransferDataClient) Send(m *UploadData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageBoardTransferDataClient) CloseAndRecv() (*UploadACK, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadACK)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageBoardClient) SignalNewTail(ctx context.Context, in *SyncTailsRequest, opts ...grpc.CallOption) (*SyncTailsACK, error) {
	out := new(SyncTailsACK)
	err := c.cc.Invoke(ctx, MessageBoard_SignalNewTail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) HeartBeat(ctx context.Context, in *HearthBeatRequest, opts ...grpc.CallOption) (*HearthBeatResponse, error) {
	out := new(HearthBeatResponse)
	err := c.cc.Invoke(ctx, MessageBoard_HeartBeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) AssignChainNode(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*ACK, error) {
	out := new(ACK)
	err := c.cc.Invoke(ctx, MessageBoard_AssignChainNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ForwardBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, MessageBoard_ForwardBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ReadLike(ctx context.Context, in *ReadLikeRequest, opts ...grpc.CallOption) (*Like, error) {
	out := new(Like)
	err := c.cc.Invoke(ctx, MessageBoard_ReadLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ReadUser(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, MessageBoard_ReadUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ReadTopic(ctx context.Context, in *ReadTopicRequest, opts ...grpc.CallOption) (*Topic, error) {
	out := new(Topic)
	err := c.cc.Invoke(ctx, MessageBoard_ReadTopic_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ReadMessage(ctx context.Context, in *ReadMessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, MessageBoard_ReadMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ListTopicsFromInner(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTopicsResponse, error) {
	out := new(ListTopicsResponse)
	err := c.cc.Invoke(ctx, MessageBoard_ListTopicsFromInner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageBoardClient) ListMessagesFromInner(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListMessagesResponse, error) {
	out := new(ListMessagesResponse)
	err := c.cc.Invoke(ctx, MessageBoard_ListMessagesFromInner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageBoardServer is the server API for MessageBoard service.
// All implementations must embed UnimplementedMessageBoardServer
// for forward compatibility
type MessageBoardServer interface {
	// Creates a new user and assigns it an id
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	// Creates a new topic to which users can post messages
	CreateTopic(context.Context, *CreateTopicRequest) (*Topic, error)
	// Post a message to a topic; Succed only if the User and the Topic exist in the data base.
	PostMessage(context.Context, *PostMessageRequest) (*Message, error)
	// Update an existing message. Allowed only for the user who posted the message.
	UpdateMessage(context.Context, *UpdateMessageRequest) (*Message, error)
	// Delete an existing message. Allowed only for the user who posted the message.
	DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error)
	// Like an existing message. Return the message with the new number of likes.
	LikeMessage(context.Context, *LikeMessageRequest) (*Message, error)
	// Request a node to which a subscription can be opened.
	GetSubscriptionNode(context.Context, *SubscriptionNodeRequest) (*SubscriptionNodeResponse, error)
	// Returns all the topics
	ListTopics(context.Context, *emptypb.Empty) (*ListTopicsResponse, error)
	// Returns messages in a topic
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	// Subscribe to topics; goes to the node returned by head
	SubscribeTopic(*SubscribeTopicRequest, MessageBoard_SubscribeTopicServer) error
	// Sync the old tail and the new tail
	TransferData(MessageBoard_TransferDataServer) error
	// Signal that a new tail has been added
	SignalNewTail(context.Context, *SyncTailsRequest) (*SyncTailsACK, error)
	HeartBeat(context.Context, *HearthBeatRequest) (*HearthBeatResponse, error)
	AssignChainNode(context.Context, *AssignRequest) (*ACK, error)
	ForwardBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	ReadLike(context.Context, *ReadLikeRequest) (*Like, error)
	ReadUser(context.Context, *ReadUserRequest) (*User, error)
	ReadTopic(context.Context, *ReadTopicRequest) (*Topic, error)
	ReadMessage(context.Context, *ReadMessageRequest) (*Message, error)
	ListTopicsFromInner(context.Context, *emptypb.Empty) (*ListTopicsResponse, error)
	ListMessagesFromInner(context.Context, *emptypb.Empty) (*ListMessagesResponse, error)
	mustEmbedUnimplementedMessageBoardServer()
}

// UnimplementedMessageBoardServer must be embedded to have forward compatible implementations.
type UnimplementedMessageBoardServer struct {
}

func (UnimplementedMessageBoardServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMessageBoardServer) CreateTopic(context.Context, *CreateTopicRequest) (*Topic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedMessageBoardServer) PostMessage(context.Context, *PostMessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedMessageBoardServer) UpdateMessage(context.Context, *UpdateMessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMessage not implemented")
}
func (UnimplementedMessageBoardServer) DeleteMessage(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedMessageBoardServer) LikeMessage(context.Context, *LikeMessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeMessage not implemented")
}
func (UnimplementedMessageBoardServer) GetSubscriptionNode(context.Context, *SubscriptionNodeRequest) (*SubscriptionNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptionNode not implemented")
}
func (UnimplementedMessageBoardServer) ListTopics(context.Context, *emptypb.Empty) (*ListTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedMessageBoardServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedMessageBoardServer) SubscribeTopic(*SubscribeTopicRequest, MessageBoard_SubscribeTopicServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTopic not implemented")
}
func (UnimplementedMessageBoardServer) TransferData(MessageBoard_TransferDataServer) error {
	return status.Errorf(codes.Unimplemented, "method TransferData not implemented")
}
func (UnimplementedMessageBoardServer) SignalNewTail(context.Context, *SyncTailsRequest) (*SyncTailsACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalNewTail not implemented")
}
func (UnimplementedMessageBoardServer) HeartBeat(context.Context, *HearthBeatRequest) (*HearthBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedMessageBoardServer) AssignChainNode(context.Context, *AssignRequest) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignChainNode not implemented")
}
func (UnimplementedMessageBoardServer) ForwardBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardBatch not implemented")
}
func (UnimplementedMessageBoardServer) ReadLike(context.Context, *ReadLikeRequest) (*Like, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadLike not implemented")
}
func (UnimplementedMessageBoardServer) ReadUser(context.Context, *ReadUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (UnimplementedMessageBoardServer) ReadTopic(context.Context, *ReadTopicRequest) (*Topic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTopic not implemented")
}
func (UnimplementedMessageBoardServer) ReadMessage(context.Context, *ReadMessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMessage not implemented")
}
func (UnimplementedMessageBoardServer) ListTopicsFromInner(context.Context, *emptypb.Empty) (*ListTopicsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopicsFromInner not implemented")
}
func (UnimplementedMessageBoardServer) ListMessagesFromInner(context.Context, *emptypb.Empty) (*ListMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMessagesFromInner not implemented")
}
func (UnimplementedMessageBoardServer) mustEmbedUnimplementedMessageBoardServer() {}

// UnsafeMessageBoardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageBoardServer will
// result in compilation errors.
type UnsafeMessageBoardServer interface {
	mustEmbedUnimplementedMessageBoardServer()
}

func RegisterMessageBoardServer(s grpc.ServiceRegistrar, srv MessageBoardServer) {
	s.RegisterService(&MessageBoard_ServiceDesc, srv)
}

func _MessageBoard_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_UpdateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).UpdateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_UpdateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).UpdateMessage(ctx, req.(*UpdateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).DeleteMessage(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_LikeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).LikeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_LikeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).LikeMessage(ctx, req.(*LikeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_GetSubscriptionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscriptionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).GetSubscriptionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_GetSubscriptionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).GetSubscriptionNode(ctx, req.(*SubscriptionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ListTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ListTopics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_SubscribeTopic_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTopicRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageBoardServer).SubscribeTopic(m, &messageBoardSubscribeTopicServer{stream})
}

type MessageBoard_SubscribeTopicServer interface {
	Send(*MessageEvent) error
	grpc.ServerStream
}

type messageBoardSubscribeTopicServer struct {
	grpc.ServerStream
}

func (x *messageBoardSubscribeTopicServer) Send(m *MessageEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _MessageBoard_TransferData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageBoardServer).TransferData(&messageBoardTransferDataServer{stream})
}

type MessageBoard_TransferDataServer interface {
	SendAndClose(*UploadACK) error
	Recv() (*UploadData, error)
	grpc.ServerStream
}

type messageBoardTransferDataServer struct {
	grpc.ServerStream
}

func (x *messageBoardTransferDataServer) SendAndClose(m *UploadACK) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageBoardTransferDataServer) Recv() (*UploadData, error) {
	m := new(UploadData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MessageBoard_SignalNewTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).SignalNewTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_SignalNewTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).SignalNewTail(ctx, req.(*SyncTailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HearthBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).HeartBeat(ctx, req.(*HearthBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_AssignChainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).AssignChainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_AssignChainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).AssignChainNode(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ForwardBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ForwardBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ForwardBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ForwardBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ReadLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ReadLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ReadLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ReadLike(ctx, req.(*ReadLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ReadUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ReadUser(ctx, req.(*ReadUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ReadTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ReadTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ReadTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ReadTopic(ctx, req.(*ReadTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ReadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ReadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ReadMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ReadMessage(ctx, req.(*ReadMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ListTopicsFromInner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ListTopicsFromInner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ListTopicsFromInner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ListTopicsFromInner(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageBoard_ListMessagesFromInner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageBoardServer).ListMessagesFromInner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageBoard_ListMessagesFromInner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageBoardServer).ListMessagesFromInner(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageBoard_ServiceDesc is the grpc.ServiceDesc for MessageBoard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageBoard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.MessageBoard",
	HandlerType: (*MessageBoardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _MessageBoard_CreateUser_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _MessageBoard_CreateTopic_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _MessageBoard_PostMessage_Handler,
		},
		{
			MethodName: "UpdateMessage",
			Handler:    _MessageBoard_UpdateMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _MessageBoard_DeleteMessage_Handler,
		},
		{
			MethodName: "LikeMessage",
			Handler:    _MessageBoard_LikeMessage_Handler,
		},
		{
			MethodName: "GetSubscriptionNode",
			Handler:    _MessageBoard_GetSubscriptionNode_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _MessageBoard_ListTopics_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _MessageBoard_GetMessages_Handler,
		},
		{
			MethodName: "SignalNewTail",
			Handler:    _MessageBoard_SignalNewTail_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _MessageBoard_HeartBeat_Handler,
		},
		{
			MethodName: "AssignChainNode",
			Handler:    _MessageBoard_AssignChainNode_Handler,
		},
		{
			MethodName: "ForwardBatch",
			Handler:    _MessageBoard_ForwardBatch_Handler,
		},
		{
			MethodName: "ReadLike",
			Handler:    _MessageBoard_ReadLike_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _MessageBoard_ReadUser_Handler,
		},
		{
			MethodName: "ReadTopic",
			Handler:    _MessageBoard_ReadTopic_Handler,
		},
		{
			MethodName: "ReadMessage",
			Handler:    _MessageBoard_ReadMessage_Handler,
		},
		{
			MethodName: "ListTopicsFromInner",
			Handler:    _MessageBoard_ListTopicsFromInner_Handler,
		},
		{
			MethodName: "ListMessagesFromInner",
			Handler:    _MessageBoard_ListMessagesFromInner_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTopic",
			Handler:       _MessageBoard_SubscribeTopic_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TransferData",
			Handler:       _MessageBoard_TransferData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf.proto",
}

const (
	ChainNode_Read_FullMethodName = "/razpravljalnica.ChainNode/Read"
)

// ChainNodeClient is the client API for ChainNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainNodeClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type chainNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewChainNodeClient(cc grpc.ClientConnInterface) ChainNodeClient {
	return &chainNodeClient{cc}
}

func (c *chainNodeClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, ChainNode_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainNodeServer is the server API for ChainNode service.
// All implementations must embed UnimplementedChainNodeServer
// for forward compatibility
type ChainNodeServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	mustEmbedUnimplementedChainNodeServer()
}

// UnimplementedChainNodeServer must be embedded to have forward compatible implementations.
type UnimplementedChainNodeServer struct {
}

func (UnimplementedChainNodeServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedChainNodeServer) mustEmbedUnimplementedChainNodeServer() {}

// UnsafeChainNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainNodeServer will
// result in compilation errors.
type UnsafeChainNodeServer interface {
	mustEmbedUnimplementedChainNodeServer()
}

func RegisterChainNodeServer(s grpc.ServiceRegistrar, srv ChainNodeServer) {
	s.RegisterService(&ChainNode_ServiceDesc, srv)
}

func _ChainNode_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainNodeServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainNode_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainNodeServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainNode_ServiceDesc is the grpc.ServiceDesc for ChainNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.ChainNode",
	HandlerType: (*ChainNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _ChainNode_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}

const (
	MasterNode_SignalAlive_FullMethodName        = "/razpravljalnica.MasterNode/SignalAlive"
	MasterNode_ReadFromNodes_FullMethodName      = "/razpravljalnica.MasterNode/ReadFromNodes"
	MasterNode_GetClusterState_FullMethodName    = "/razpravljalnica.MasterNode/GetClusterState"
	MasterNode_GenerateRandomNode_FullMethodName = "/razpravljalnica.MasterNode/GenerateRandomNode"
	MasterNode_SignalNewTail_FullMethodName      = "/razpravljalnica.MasterNode/SignalNewTail"
)

// MasterNodeClient is the client API for MasterNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterNodeClient interface {
	SignalAlive(ctx context.Context, in *SignalAliveRequest, opts ...grpc.CallOption) (*SignalAliveResponse, error)
	ReadFromNodes(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClusterStateResponse, error)
	GenerateRandomNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GenerateRandomNodeResponse, error)
	SignalNewTail(ctx context.Context, in *NewTailRequest, opts ...grpc.CallOption) (*NewTailResponse, error)
}

type masterNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterNodeClient(cc grpc.ClientConnInterface) MasterNodeClient {
	return &masterNodeClient{cc}
}

func (c *masterNodeClient) SignalAlive(ctx context.Context, in *SignalAliveRequest, opts ...grpc.CallOption) (*SignalAliveResponse, error) {
	out := new(SignalAliveResponse)
	err := c.cc.Invoke(ctx, MasterNode_SignalAlive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) ReadFromNodes(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, MasterNode_ReadFromNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClusterStateResponse, error) {
	out := new(GetClusterStateResponse)
	err := c.cc.Invoke(ctx, MasterNode_GetClusterState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) GenerateRandomNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GenerateRandomNodeResponse, error) {
	out := new(GenerateRandomNodeResponse)
	err := c.cc.Invoke(ctx, MasterNode_GenerateRandomNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) SignalNewTail(ctx context.Context, in *NewTailRequest, opts ...grpc.CallOption) (*NewTailResponse, error) {
	out := new(NewTailResponse)
	err := c.cc.Invoke(ctx, MasterNode_SignalNewTail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterNodeServer is the server API for MasterNode service.
// All implementations must embed UnimplementedMasterNodeServer
// for forward compatibility
type MasterNodeServer interface {
	SignalAlive(context.Context, *SignalAliveRequest) (*SignalAliveResponse, error)
	ReadFromNodes(context.Context, *ReadRequest) (*ReadResponse, error)
	GetClusterState(context.Context, *emptypb.Empty) (*GetClusterStateResponse, error)
	GenerateRandomNode(context.Context, *emptypb.Empty) (*GenerateRandomNodeResponse, error)
	SignalNewTail(context.Context, *NewTailRequest) (*NewTailResponse, error)
	mustEmbedUnimplementedMasterNodeServer()
}

// UnimplementedMasterNodeServer must be embedded to have forward compatible implementations.
type UnimplementedMasterNodeServer struct {
}

func (UnimplementedMasterNodeServer) SignalAlive(context.Context, *SignalAliveRequest) (*SignalAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalAlive not implemented")
}
func (UnimplementedMasterNodeServer) ReadFromNodes(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFromNodes not implemented")
}
func (UnimplementedMasterNodeServer) GetClusterState(context.Context, *emptypb.Empty) (*GetClusterStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterState not implemented")
}
func (UnimplementedMasterNodeServer) GenerateRandomNode(context.Context, *emptypb.Empty) (*GenerateRandomNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRandomNode not implemented")
}
func (UnimplementedMasterNodeServer) SignalNewTail(context.Context, *NewTailRequest) (*NewTailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalNewTail not implemented")
}
func (UnimplementedMasterNodeServer) mustEmbedUnimplementedMasterNodeServer() {}

// UnsafeMasterNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterNodeServer will
// result in compilation errors.
type UnsafeMasterNodeServer interface {
	mustEmbedUnimplementedMasterNodeServer()
}

func RegisterMasterNodeServer(s grpc.ServiceRegistrar, srv MasterNodeServer) {
	s.RegisterService(&MasterNode_ServiceDesc, srv)
}

func _MasterNode_SignalAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).SignalAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_SignalAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).SignalAlive(ctx, req.(*SignalAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_ReadFromNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).ReadFromNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_ReadFromNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).ReadFromNodes(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_GetClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).GetClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_GetClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).GetClusterState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_GenerateRandomNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).GenerateRandomNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_GenerateRandomNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).GenerateRandomNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_SignalNewTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).SignalNewTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_SignalNewTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).SignalNewTail(ctx, req.(*NewTailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterNode_ServiceDesc is the grpc.ServiceDesc for MasterNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.MasterNode",
	HandlerType: (*MasterNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignalAlive",
			Handler:    _MasterNode_SignalAlive_Handler,
		},
		{
			MethodName: "ReadFromNodes",
			Handler:    _MasterNode_ReadFromNodes_Handler,
		},
		{
			MethodName: "GetClusterState",
			Handler:    _MasterNode_GetClusterState_Handler,
		},
		{
			MethodName: "GenerateRandomNode",
			Handler:    _MasterNode_GenerateRandomNode_Handler,
		},
		{
			MethodName: "SignalNewTail",
			Handler:    _MasterNode_SignalNewTail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}
