// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/grpc/protobufInternal/protobufInt.proto

package protobufInt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChainNode_Read_FullMethodName = "/protobufInternal.ChainNode/Read"
)

// ChainNodeClient is the client API for ChainNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainNodeClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type chainNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewChainNodeClient(cc grpc.ClientConnInterface) ChainNodeClient {
	return &chainNodeClient{cc}
}

func (c *chainNodeClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, ChainNode_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainNodeServer is the server API for ChainNode service.
// All implementations must embed UnimplementedChainNodeServer
// for forward compatibility
type ChainNodeServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	mustEmbedUnimplementedChainNodeServer()
}

// UnimplementedChainNodeServer must be embedded to have forward compatible implementations.
type UnimplementedChainNodeServer struct {
}

func (UnimplementedChainNodeServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedChainNodeServer) mustEmbedUnimplementedChainNodeServer() {}

// UnsafeChainNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainNodeServer will
// result in compilation errors.
type UnsafeChainNodeServer interface {
	mustEmbedUnimplementedChainNodeServer()
}

func RegisterChainNodeServer(s grpc.ServiceRegistrar, srv ChainNodeServer) {
	s.RegisterService(&ChainNode_ServiceDesc, srv)
}

func _ChainNode_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainNodeServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainNode_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainNodeServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainNode_ServiceDesc is the grpc.ServiceDesc for ChainNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufInternal.ChainNode",
	HandlerType: (*ChainNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _ChainNode_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/protobufInternal/protobufInt.proto",
}

const (
	MasterNode_SignalAlive_FullMethodName               = "/protobufInternal.MasterNode/SignalAlive"
	MasterNode_ReadFromNodes_FullMethodName             = "/protobufInternal.MasterNode/ReadFromNodes"
	MasterNode_GetClusterState_FullMethodName           = "/protobufInternal.MasterNode/GetClusterState"
	MasterNode_GenerateRandomNodeForRead_FullMethodName = "/protobufInternal.MasterNode/GenerateRandomNodeForRead"
	MasterNode_SignalNewTail_FullMethodName             = "/protobufInternal.MasterNode/SignalNewTail"
)

// MasterNodeClient is the client API for MasterNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterNodeClient interface {
	SignalAlive(ctx context.Context, in *SignalAliveRequest, opts ...grpc.CallOption) (*SignalAliveResponse, error)
	ReadFromNodes(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClusterStateResponse, error)
	GenerateRandomNodeForRead(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GenerateRandomNodeResponse, error)
	SignalNewTail(ctx context.Context, in *NewTailRequest, opts ...grpc.CallOption) (*NewTailResponse, error)
}

type masterNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterNodeClient(cc grpc.ClientConnInterface) MasterNodeClient {
	return &masterNodeClient{cc}
}

func (c *masterNodeClient) SignalAlive(ctx context.Context, in *SignalAliveRequest, opts ...grpc.CallOption) (*SignalAliveResponse, error) {
	out := new(SignalAliveResponse)
	err := c.cc.Invoke(ctx, MasterNode_SignalAlive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) ReadFromNodes(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, MasterNode_ReadFromNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) GetClusterState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetClusterStateResponse, error) {
	out := new(GetClusterStateResponse)
	err := c.cc.Invoke(ctx, MasterNode_GetClusterState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) GenerateRandomNodeForRead(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GenerateRandomNodeResponse, error) {
	out := new(GenerateRandomNodeResponse)
	err := c.cc.Invoke(ctx, MasterNode_GenerateRandomNodeForRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) SignalNewTail(ctx context.Context, in *NewTailRequest, opts ...grpc.CallOption) (*NewTailResponse, error) {
	out := new(NewTailResponse)
	err := c.cc.Invoke(ctx, MasterNode_SignalNewTail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterNodeServer is the server API for MasterNode service.
// All implementations must embed UnimplementedMasterNodeServer
// for forward compatibility
type MasterNodeServer interface {
	SignalAlive(context.Context, *SignalAliveRequest) (*SignalAliveResponse, error)
	ReadFromNodes(context.Context, *ReadRequest) (*ReadResponse, error)
	GetClusterState(context.Context, *emptypb.Empty) (*GetClusterStateResponse, error)
	GenerateRandomNodeForRead(context.Context, *emptypb.Empty) (*GenerateRandomNodeResponse, error)
	SignalNewTail(context.Context, *NewTailRequest) (*NewTailResponse, error)
	mustEmbedUnimplementedMasterNodeServer()
}

// UnimplementedMasterNodeServer must be embedded to have forward compatible implementations.
type UnimplementedMasterNodeServer struct {
}

func (UnimplementedMasterNodeServer) SignalAlive(context.Context, *SignalAliveRequest) (*SignalAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalAlive not implemented")
}
func (UnimplementedMasterNodeServer) ReadFromNodes(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFromNodes not implemented")
}
func (UnimplementedMasterNodeServer) GetClusterState(context.Context, *emptypb.Empty) (*GetClusterStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterState not implemented")
}
func (UnimplementedMasterNodeServer) GenerateRandomNodeForRead(context.Context, *emptypb.Empty) (*GenerateRandomNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRandomNodeForRead not implemented")
}
func (UnimplementedMasterNodeServer) SignalNewTail(context.Context, *NewTailRequest) (*NewTailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalNewTail not implemented")
}
func (UnimplementedMasterNodeServer) mustEmbedUnimplementedMasterNodeServer() {}

// UnsafeMasterNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterNodeServer will
// result in compilation errors.
type UnsafeMasterNodeServer interface {
	mustEmbedUnimplementedMasterNodeServer()
}

func RegisterMasterNodeServer(s grpc.ServiceRegistrar, srv MasterNodeServer) {
	s.RegisterService(&MasterNode_ServiceDesc, srv)
}

func _MasterNode_SignalAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).SignalAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_SignalAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).SignalAlive(ctx, req.(*SignalAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_ReadFromNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).ReadFromNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_ReadFromNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).ReadFromNodes(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_GetClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).GetClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_GetClusterState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).GetClusterState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_GenerateRandomNodeForRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).GenerateRandomNodeForRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_GenerateRandomNodeForRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).GenerateRandomNodeForRead(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_SignalNewTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).SignalNewTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_SignalNewTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).SignalNewTail(ctx, req.(*NewTailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterNode_ServiceDesc is the grpc.ServiceDesc for MasterNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufInternal.MasterNode",
	HandlerType: (*MasterNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignalAlive",
			Handler:    _MasterNode_SignalAlive_Handler,
		},
		{
			MethodName: "ReadFromNodes",
			Handler:    _MasterNode_ReadFromNodes_Handler,
		},
		{
			MethodName: "GetClusterState",
			Handler:    _MasterNode_GetClusterState_Handler,
		},
		{
			MethodName: "GenerateRandomNodeForRead",
			Handler:    _MasterNode_GenerateRandomNodeForRead_Handler,
		},
		{
			MethodName: "SignalNewTail",
			Handler:    _MasterNode_SignalNewTail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/protobufInternal/protobufInt.proto",
}
