// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v6.30.2
// source: protobufInt.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// import "google/protobuf/empty.proto";
// import "google/protobuf/timestamp.proto";
// /////////////////////////////////////////////////////
// Chain node types
// /////////////////////////////////////////////////////
type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SignalAliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId  int64  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeUrl string `protobuf:"bytes,2,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
}

func (x *SignalAliveRequest) Reset() {
	*x = SignalAliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAliveRequest) ProtoMessage() {}

func (x *SignalAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAliveRequest.ProtoReflect.Descriptor instead.
func (*SignalAliveRequest) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{1}
}

func (x *SignalAliveRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SignalAliveRequest) GetNodeUrl() string {
	if x != nil {
		return x.NodeUrl
	}
	return ""
}

type SignalAliveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterUrl string `protobuf:"bytes,1,opt,name=masterUrl,proto3" json:"masterUrl,omitempty"`
}

func (x *SignalAliveResponse) Reset() {
	*x = SignalAliveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAliveResponse) ProtoMessage() {}

func (x *SignalAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAliveResponse.ProtoReflect.Descriptor instead.
func (*SignalAliveResponse) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{2}
}

func (x *SignalAliveResponse) GetMasterUrl() string {
	if x != nil {
		return x.MasterUrl
	}
	return ""
}

type HearthBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HearthBeatResponse) Reset() {
	*x = HearthBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HearthBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HearthBeatResponse) ProtoMessage() {}

func (x *HearthBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HearthBeatResponse.ProtoReflect.Descriptor instead.
func (*HearthBeatResponse) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{3}
}

func (x *HearthBeatResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HearthBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HearthBeatRequest) Reset() {
	*x = HearthBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HearthBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HearthBeatRequest) ProtoMessage() {}

func (x *HearthBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HearthBeatRequest.ProtoReflect.Descriptor instead.
func (*HearthBeatRequest) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{4}
}

func (x *HearthBeatRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ACK) Reset() {
	*x = ACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACK) ProtoMessage() {}

func (x *ACK) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACK.ProtoReflect.Descriptor instead.
func (*ACK) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{5}
}

func (x *ACK) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AssignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextUrl string `protobuf:"bytes,1,opt,name=nextUrl,proto3" json:"nextUrl,omitempty"`
	PrevUrl string `protobuf:"bytes,2,opt,name=prevUrl,proto3" json:"prevUrl,omitempty"`
	Id      int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{6}
}

func (x *AssignRequest) GetNextUrl() string {
	if x != nil {
		return x.NextUrl
	}
	return ""
}

func (x *AssignRequest) GetPrevUrl() string {
	if x != nil {
		return x.PrevUrl
	}
	return ""
}

func (x *AssignRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ForwardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{7}
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int64 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobufInt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufInt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_protobufInt_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

var File_protobufInt_proto protoreflect.FileDescriptor

var file_protobufInt_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c,
	0x6e, 0x69, 0x63, 0x61, 0x22, 0x16, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x12,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64,
	0x65, 0x55, 0x72, 0x6c, 0x22, 0x33, 0x0a, 0x13, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x24, 0x0a, 0x12, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x68, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x23, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x68, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x53, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x55, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x78, 0x74, 0x55, 0x72, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x55, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x0d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0xec, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x54, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x22, 0x2e, 0x72,
	0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x68, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69,
	0x63, 0x61, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x68, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72,
	0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72,
	0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x41, 0x43, 0x4b, 0x12, 0x40,
	0x0a, 0x07, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x72, 0x61, 0x7a, 0x70,
	0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x61, 0x7a,
	0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x41, 0x43, 0x4b,
	0x32, 0xa6, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x58, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x23,
	0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61,
	0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61,
	0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61,
	0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x41, 0x43, 0x4b, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x72, 0x61,
	0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobufInt_proto_rawDescOnce sync.Once
	file_protobufInt_proto_rawDescData = file_protobufInt_proto_rawDesc
)

func file_protobufInt_proto_rawDescGZIP() []byte {
	file_protobufInt_proto_rawDescOnce.Do(func() {
		file_protobufInt_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobufInt_proto_rawDescData)
	})
	return file_protobufInt_proto_rawDescData
}

var file_protobufInt_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protobufInt_proto_goTypes = []interface{}{
	(*Node)(nil),                // 0: razpravljalnica.Node
	(*SignalAliveRequest)(nil),  // 1: razpravljalnica.SignalAliveRequest
	(*SignalAliveResponse)(nil), // 2: razpravljalnica.SignalAliveResponse
	(*HearthBeatResponse)(nil),  // 3: razpravljalnica.HearthBeatResponse
	(*HearthBeatRequest)(nil),   // 4: razpravljalnica.HearthBeatRequest
	(*ACK)(nil),                 // 5: razpravljalnica.ACK
	(*AssignRequest)(nil),       // 6: razpravljalnica.AssignRequest
	(*ForwardRequest)(nil),      // 7: razpravljalnica.ForwardRequest
	(*UpdateRequest)(nil),       // 8: razpravljalnica.UpdateRequest
}
var file_protobufInt_proto_depIdxs = []int32{
	4, // 0: razpravljalnica.ChainNode.HeartBeat:input_type -> razpravljalnica.HearthBeatRequest
	6, // 1: razpravljalnica.ChainNode.AssignChainNode:input_type -> razpravljalnica.AssignRequest
	7, // 2: razpravljalnica.ChainNode.Forward:input_type -> razpravljalnica.ForwardRequest
	1, // 3: razpravljalnica.MasterNode.SignalAlive:input_type -> razpravljalnica.SignalAliveRequest
	8, // 4: razpravljalnica.MasterNode.Update:input_type -> razpravljalnica.UpdateRequest
	3, // 5: razpravljalnica.ChainNode.HeartBeat:output_type -> razpravljalnica.HearthBeatResponse
	5, // 6: razpravljalnica.ChainNode.AssignChainNode:output_type -> razpravljalnica.ACK
	5, // 7: razpravljalnica.ChainNode.Forward:output_type -> razpravljalnica.ACK
	2, // 8: razpravljalnica.MasterNode.SignalAlive:output_type -> razpravljalnica.SignalAliveResponse
	5, // 9: razpravljalnica.MasterNode.Update:output_type -> razpravljalnica.ACK
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobufInt_proto_init() }
func file_protobufInt_proto_init() {
	if File_protobufInt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobufInt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalAliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalAliveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HearthBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HearthBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobufInt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobufInt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_protobufInt_proto_goTypes,
		DependencyIndexes: file_protobufInt_proto_depIdxs,
		MessageInfos:      file_protobufInt_proto_msgTypes,
	}.Build()
	File_protobufInt_proto = out.File
	file_protobufInt_proto_rawDesc = nil
	file_protobufInt_proto_goTypes = nil
	file_protobufInt_proto_depIdxs = nil
}
