// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: protobufInt.proto

package razpravljalnica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChainNode_HeartBeat_FullMethodName       = "/razpravljalnica.ChainNode/HeartBeat"
	ChainNode_AssignChainNode_FullMethodName = "/razpravljalnica.ChainNode/AssignChainNode"
	ChainNode_Forward_FullMethodName         = "/razpravljalnica.ChainNode/Forward"
)

// ChainNodeClient is the client API for ChainNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainNodeClient interface {
	HeartBeat(ctx context.Context, in *HearthBeatRequest, opts ...grpc.CallOption) (*HearthBeatResponse, error)
	AssignChainNode(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*ACK, error)
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ACK, error)
}

type chainNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewChainNodeClient(cc grpc.ClientConnInterface) ChainNodeClient {
	return &chainNodeClient{cc}
}

func (c *chainNodeClient) HeartBeat(ctx context.Context, in *HearthBeatRequest, opts ...grpc.CallOption) (*HearthBeatResponse, error) {
	out := new(HearthBeatResponse)
	err := c.cc.Invoke(ctx, ChainNode_HeartBeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainNodeClient) AssignChainNode(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*ACK, error) {
	out := new(ACK)
	err := c.cc.Invoke(ctx, ChainNode_AssignChainNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chainNodeClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ACK, error) {
	out := new(ACK)
	err := c.cc.Invoke(ctx, ChainNode_Forward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainNodeServer is the server API for ChainNode service.
// All implementations must embed UnimplementedChainNodeServer
// for forward compatibility
type ChainNodeServer interface {
	HeartBeat(context.Context, *HearthBeatRequest) (*HearthBeatResponse, error)
	AssignChainNode(context.Context, *AssignRequest) (*ACK, error)
	Forward(context.Context, *ForwardRequest) (*ACK, error)
	mustEmbedUnimplementedChainNodeServer()
}

// UnimplementedChainNodeServer must be embedded to have forward compatible implementations.
type UnimplementedChainNodeServer struct {
}

func (UnimplementedChainNodeServer) HeartBeat(context.Context, *HearthBeatRequest) (*HearthBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}
func (UnimplementedChainNodeServer) AssignChainNode(context.Context, *AssignRequest) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignChainNode not implemented")
}
func (UnimplementedChainNodeServer) Forward(context.Context, *ForwardRequest) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedChainNodeServer) mustEmbedUnimplementedChainNodeServer() {}

// UnsafeChainNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainNodeServer will
// result in compilation errors.
type UnsafeChainNodeServer interface {
	mustEmbedUnimplementedChainNodeServer()
}

func RegisterChainNodeServer(s grpc.ServiceRegistrar, srv ChainNodeServer) {
	s.RegisterService(&ChainNode_ServiceDesc, srv)
}

func _ChainNode_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HearthBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainNodeServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainNode_HeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainNodeServer).HeartBeat(ctx, req.(*HearthBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainNode_AssignChainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainNodeServer).AssignChainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainNode_AssignChainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainNodeServer).AssignChainNode(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChainNode_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainNodeServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainNode_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainNodeServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainNode_ServiceDesc is the grpc.ServiceDesc for ChainNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.ChainNode",
	HandlerType: (*ChainNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HeartBeat",
			Handler:    _ChainNode_HeartBeat_Handler,
		},
		{
			MethodName: "AssignChainNode",
			Handler:    _ChainNode_AssignChainNode_Handler,
		},
		{
			MethodName: "Forward",
			Handler:    _ChainNode_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufInt.proto",
}

const (
	MasterNode_SignalAlive_FullMethodName = "/razpravljalnica.MasterNode/SignalAlive"
	MasterNode_Update_FullMethodName      = "/razpravljalnica.MasterNode/Update"
)

// MasterNodeClient is the client API for MasterNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterNodeClient interface {
	SignalAlive(ctx context.Context, in *SignalAliveRequest, opts ...grpc.CallOption) (*SignalAliveResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ACK, error)
}

type masterNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterNodeClient(cc grpc.ClientConnInterface) MasterNodeClient {
	return &masterNodeClient{cc}
}

func (c *masterNodeClient) SignalAlive(ctx context.Context, in *SignalAliveRequest, opts ...grpc.CallOption) (*SignalAliveResponse, error) {
	out := new(SignalAliveResponse)
	err := c.cc.Invoke(ctx, MasterNode_SignalAlive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterNodeClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ACK, error) {
	out := new(ACK)
	err := c.cc.Invoke(ctx, MasterNode_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterNodeServer is the server API for MasterNode service.
// All implementations must embed UnimplementedMasterNodeServer
// for forward compatibility
type MasterNodeServer interface {
	SignalAlive(context.Context, *SignalAliveRequest) (*SignalAliveResponse, error)
	Update(context.Context, *UpdateRequest) (*ACK, error)
	mustEmbedUnimplementedMasterNodeServer()
}

// UnimplementedMasterNodeServer must be embedded to have forward compatible implementations.
type UnimplementedMasterNodeServer struct {
}

func (UnimplementedMasterNodeServer) SignalAlive(context.Context, *SignalAliveRequest) (*SignalAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignalAlive not implemented")
}
func (UnimplementedMasterNodeServer) Update(context.Context, *UpdateRequest) (*ACK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedMasterNodeServer) mustEmbedUnimplementedMasterNodeServer() {}

// UnsafeMasterNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterNodeServer will
// result in compilation errors.
type UnsafeMasterNodeServer interface {
	mustEmbedUnimplementedMasterNodeServer()
}

func RegisterMasterNodeServer(s grpc.ServiceRegistrar, srv MasterNodeServer) {
	s.RegisterService(&MasterNode_ServiceDesc, srv)
}

func _MasterNode_SignalAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).SignalAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_SignalAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).SignalAlive(ctx, req.(*SignalAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterNode_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterNodeServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterNode_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterNodeServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterNode_ServiceDesc is the grpc.ServiceDesc for MasterNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.MasterNode",
	HandlerType: (*MasterNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignalAlive",
			Handler:    _MasterNode_SignalAlive_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MasterNode_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufInt.proto",
}
