// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.2
// source: protobuf.proto

package razpravljalnica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ChainNode_HearthBeat_FullMethodName = "/razpravljalnica.ChainNode/HearthBeat"
)

// ChainNodeClient is the client API for ChainNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChainNodeClient interface {
	HearthBeat(ctx context.Context, in *HearthBeatRequest, opts ...grpc.CallOption) (*HearthBeatResponse, error)
}

type chainNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewChainNodeClient(cc grpc.ClientConnInterface) ChainNodeClient {
	return &chainNodeClient{cc}
}

func (c *chainNodeClient) HearthBeat(ctx context.Context, in *HearthBeatRequest, opts ...grpc.CallOption) (*HearthBeatResponse, error) {
	out := new(HearthBeatResponse)
	err := c.cc.Invoke(ctx, ChainNode_HearthBeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChainNodeServer is the server API for ChainNode service.
// All implementations must embed UnimplementedChainNodeServer
// for forward compatibility
type ChainNodeServer interface {
	HearthBeat(context.Context, *HearthBeatRequest) (*HearthBeatResponse, error)
	mustEmbedUnimplementedChainNodeServer()
}

// UnimplementedChainNodeServer must be embedded to have forward compatible implementations.
type UnimplementedChainNodeServer struct {
}

func (UnimplementedChainNodeServer) HearthBeat(context.Context, *HearthBeatRequest) (*HearthBeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HearthBeat not implemented")
}
func (UnimplementedChainNodeServer) mustEmbedUnimplementedChainNodeServer() {}

// UnsafeChainNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChainNodeServer will
// result in compilation errors.
type UnsafeChainNodeServer interface {
	mustEmbedUnimplementedChainNodeServer()
}

func RegisterChainNodeServer(s grpc.ServiceRegistrar, srv ChainNodeServer) {
	s.RegisterService(&ChainNode_ServiceDesc, srv)
}

func _ChainNode_HearthBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HearthBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChainNodeServer).HearthBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChainNode_HearthBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChainNodeServer).HearthBeat(ctx, req.(*HearthBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChainNode_ServiceDesc is the grpc.ServiceDesc for ChainNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChainNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "razpravljalnica.ChainNode",
	HandlerType: (*ChainNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HearthBeat",
			Handler:    _ChainNode_HearthBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}
