// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: api/grpc/protobufInternal/protobufInt.proto

package protobufInt

import (
	protobufRazpravljalnica "PS_projekt/api/grpc/protobufRazpravljalnica"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// import "google/protobuf/timestamp.proto";
// /////////////////////////////////////////////////////
// Chain node types
// /////////////////////////////////////////////////////
type NodeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{0}
}

func (x *NodeData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type SignalAliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId  int64  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeUrl string `protobuf:"bytes,2,opt,name=nodeUrl,proto3" json:"nodeUrl,omitempty"`
}

func (x *SignalAliveRequest) Reset() {
	*x = SignalAliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAliveRequest) ProtoMessage() {}

func (x *SignalAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAliveRequest.ProtoReflect.Descriptor instead.
func (*SignalAliveRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{1}
}

func (x *SignalAliveRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SignalAliveRequest) GetNodeUrl() string {
	if x != nil {
		return x.NodeUrl
	}
	return ""
}

type SignalAliveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterUrl string `protobuf:"bytes,1,opt,name=masterUrl,proto3" json:"masterUrl,omitempty"`
}

func (x *SignalAliveResponse) Reset() {
	*x = SignalAliveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAliveResponse) ProtoMessage() {}

func (x *SignalAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAliveResponse.ProtoReflect.Descriptor instead.
func (*SignalAliveResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{2}
}

func (x *SignalAliveResponse) GetMasterUrl() string {
	if x != nil {
		return x.MasterUrl
	}
	return ""
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *NodeData `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail *NodeData `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{3}
}

func (x *GetClusterStateResponse) GetHead() *NodeData {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeData {
	if x != nil {
		return x.Tail
	}
	return nil
}

type GenerateRandomNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *NodeData `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *GenerateRandomNodeResponse) Reset() {
	*x = GenerateRandomNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRandomNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomNodeResponse) ProtoMessage() {}

func (x *GenerateRandomNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomNodeResponse.ProtoReflect.Descriptor instead.
func (*GenerateRandomNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateRandomNodeResponse) GetNode() *NodeData {
	if x != nil {
		return x.Node
	}
	return nil
}

type NewTailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *NewTailRequest) Reset() {
	*x = NewTailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTailRequest) ProtoMessage() {}

func (x *NewTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTailRequest.ProtoReflect.Descriptor instead.
func (*NewTailRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{5}
}

func (x *NewTailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NewTailRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type NewTailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succ bool `protobuf:"varint,1,opt,name=succ,proto3" json:"succ,omitempty"`
}

func (x *NewTailResponse) Reset() {
	*x = NewTailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTailResponse) ProtoMessage() {}

func (x *NewTailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTailResponse.ProtoReflect.Descriptor instead.
func (*NewTailResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{6}
}

func (x *NewTailResponse) GetSucc() bool {
	if x != nil {
		return x.Succ
	}
	return false
}

type ForwardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{7}
}

func (x *ForwardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForwardRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data int64 `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{9}
}

func (x *ReadRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data int64 `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{10}
}

func (x *ReadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReadResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users    []*protobufRazpravljalnica.User    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Messages []*protobufRazpravljalnica.Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Topics   []*protobufRazpravljalnica.Topic   `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	Likes    []*protobufRazpravljalnica.Like    `protobuf:"bytes,4,rep,name=likes,proto3" json:"likes,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP(), []int{11}
}

func (x *Data) GetUsers() []*protobufRazpravljalnica.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Data) GetMessages() []*protobufRazpravljalnica.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Data) GetTopics() []*protobufRazpravljalnica.Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Data) GetLikes() []*protobufRazpravljalnica.Like {
	if x != nil {
		return x.Likes
	}
	return nil
}

var File_api_grpc_protobufInternal_protobufInt_proto protoreflect.FileDescriptor

var file_api_grpc_protobufInternal_protobufInt_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x52,
	0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a,
	0x08, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x33, 0x0a, 0x13, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x55, 0x72, 0x6c,
	0x22, 0x79, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x4c, 0x0a, 0x1a, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x32, 0x0a, 0x0e, 0x4e, 0x65, 0x77,
	0x54, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x25, 0x0a,
	0x0f, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x73, 0x75, 0x63, 0x63, 0x22, 0x3a, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x33, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1d, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc6, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x2b, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69,
	0x63, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x34,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61, 0x6c, 0x6e, 0x69,
	0x63, 0x61, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a,
	0x61, 0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x06, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x61, 0x7a, 0x70, 0x72, 0x61, 0x76, 0x6c, 0x6a, 0x61,
	0x6c, 0x6e, 0x69, 0x63, 0x61, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65,
	0x73, 0x32, 0x52, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x45,
	0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc0, 0x03, 0x0a, 0x0a, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x5a, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4e, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x54, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x29, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4e, 0x65, 0x77, 0x54,
	0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x50, 0x53, 0x5f, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x6b, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x49, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_protobufInternal_protobufInt_proto_rawDescOnce sync.Once
	file_api_grpc_protobufInternal_protobufInt_proto_rawDescData = file_api_grpc_protobufInternal_protobufInt_proto_rawDesc
)

func file_api_grpc_protobufInternal_protobufInt_proto_rawDescGZIP() []byte {
	file_api_grpc_protobufInternal_protobufInt_proto_rawDescOnce.Do(func() {
		file_api_grpc_protobufInternal_protobufInt_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_protobufInternal_protobufInt_proto_rawDescData)
	})
	return file_api_grpc_protobufInternal_protobufInt_proto_rawDescData
}

var file_api_grpc_protobufInternal_protobufInt_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_grpc_protobufInternal_protobufInt_proto_goTypes = []interface{}{
	(*NodeData)(nil),                        // 0: protobufInternal.NodeData
	(*SignalAliveRequest)(nil),              // 1: protobufInternal.SignalAliveRequest
	(*SignalAliveResponse)(nil),             // 2: protobufInternal.SignalAliveResponse
	(*GetClusterStateResponse)(nil),         // 3: protobufInternal.GetClusterStateResponse
	(*GenerateRandomNodeResponse)(nil),      // 4: protobufInternal.GenerateRandomNodeResponse
	(*NewTailRequest)(nil),                  // 5: protobufInternal.NewTailRequest
	(*NewTailResponse)(nil),                 // 6: protobufInternal.NewTailResponse
	(*ForwardRequest)(nil),                  // 7: protobufInternal.ForwardRequest
	(*UpdateRequest)(nil),                   // 8: protobufInternal.UpdateRequest
	(*ReadRequest)(nil),                     // 9: protobufInternal.ReadRequest
	(*ReadResponse)(nil),                    // 10: protobufInternal.ReadResponse
	(*Data)(nil),                            // 11: protobufInternal.Data
	(*protobufRazpravljalnica.User)(nil),    // 12: razpravljalnica.User
	(*protobufRazpravljalnica.Message)(nil), // 13: razpravljalnica.Message
	(*protobufRazpravljalnica.Topic)(nil),   // 14: razpravljalnica.Topic
	(*protobufRazpravljalnica.Like)(nil),    // 15: razpravljalnica.Like
	(*emptypb.Empty)(nil),                   // 16: google.protobuf.Empty
}
var file_api_grpc_protobufInternal_protobufInt_proto_depIdxs = []int32{
	0,  // 0: protobufInternal.GetClusterStateResponse.head:type_name -> protobufInternal.NodeData
	0,  // 1: protobufInternal.GetClusterStateResponse.tail:type_name -> protobufInternal.NodeData
	0,  // 2: protobufInternal.GenerateRandomNodeResponse.node:type_name -> protobufInternal.NodeData
	12, // 3: protobufInternal.Data.users:type_name -> razpravljalnica.User
	13, // 4: protobufInternal.Data.messages:type_name -> razpravljalnica.Message
	14, // 5: protobufInternal.Data.topics:type_name -> razpravljalnica.Topic
	15, // 6: protobufInternal.Data.likes:type_name -> razpravljalnica.Like
	9,  // 7: protobufInternal.ChainNode.Read:input_type -> protobufInternal.ReadRequest
	1,  // 8: protobufInternal.MasterNode.SignalAlive:input_type -> protobufInternal.SignalAliveRequest
	9,  // 9: protobufInternal.MasterNode.ReadFromNodes:input_type -> protobufInternal.ReadRequest
	16, // 10: protobufInternal.MasterNode.GetClusterState:input_type -> google.protobuf.Empty
	16, // 11: protobufInternal.MasterNode.GenerateRandomNode:input_type -> google.protobuf.Empty
	5,  // 12: protobufInternal.MasterNode.SignalNewTail:input_type -> protobufInternal.NewTailRequest
	10, // 13: protobufInternal.ChainNode.Read:output_type -> protobufInternal.ReadResponse
	2,  // 14: protobufInternal.MasterNode.SignalAlive:output_type -> protobufInternal.SignalAliveResponse
	10, // 15: protobufInternal.MasterNode.ReadFromNodes:output_type -> protobufInternal.ReadResponse
	3,  // 16: protobufInternal.MasterNode.GetClusterState:output_type -> protobufInternal.GetClusterStateResponse
	4,  // 17: protobufInternal.MasterNode.GenerateRandomNode:output_type -> protobufInternal.GenerateRandomNodeResponse
	6,  // 18: protobufInternal.MasterNode.SignalNewTail:output_type -> protobufInternal.NewTailResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_grpc_protobufInternal_protobufInt_proto_init() }
func file_api_grpc_protobufInternal_protobufInt_proto_init() {
	if File_api_grpc_protobufInternal_protobufInt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalAliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalAliveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClusterStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRandomNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protobufInternal_protobufInt_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_protobufInternal_protobufInt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_grpc_protobufInternal_protobufInt_proto_goTypes,
		DependencyIndexes: file_api_grpc_protobufInternal_protobufInt_proto_depIdxs,
		MessageInfos:      file_api_grpc_protobufInternal_protobufInt_proto_msgTypes,
	}.Build()
	File_api_grpc_protobufInternal_protobufInt_proto = out.File
	file_api_grpc_protobufInternal_protobufInt_proto_rawDesc = nil
	file_api_grpc_protobufInternal_protobufInt_proto_goTypes = nil
	file_api_grpc_protobufInternal_protobufInt_proto_depIdxs = nil
}
